version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/flask_blog/
hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 10
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  Install:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root